//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotaract_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOD
    {
        public System.Guid BODID { get; set; }
        public string Year { get; set; }
        public System.Guid Designation { get; set; }
        public System.Guid MemID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreateTS { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public System.DateTime UpdateTS { get; set; }
    }
}
