//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotaract_Admin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RotaractEntities : DbContext
    {
        public RotaractEntities()
            : base("name=RotaractEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOD> BODs { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<prez> prezs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
    }
}
