//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotaract_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_role_module
    {
        public System.Guid ID { get; set; }
        public System.Guid Role_ID { get; set; }
        public System.Guid Module_ID { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreateTS { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdateTS { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
